apiVersion: v1
kind: Service
metadata:
  name: {{ include "profile-service.fullname" . | trunc 63 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "profile-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
