replicaCount: 1

image:
  repository: ayoobki/order-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3003
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: maven-micro.com
  path: /orders
  pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
