replicaCount: 1

image:
  repository: ayoobki/profile-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3002
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: maven-micro.com
  path: /profiles
  pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
