replicaCount: 1

image:
  repository: ayoobki/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3001
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: maven-micro.com
  path: /users
  pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

